name: vine
services:
  vine_system:
    image: ${IMAGE_NAME:-vine_system:latest}
    container_name: ${CONTAINER_NAME:-vine-docker}
    privileged: true
    network_mode: "host"
    hostname: vine-docker
    labels:
      - com.vinesystem.role=runtime
      - com.vinesystem.name=vine-docker
    extra_hosts:
      - "vine-docker:127.0.1.1"

    volumes:
      # Mount the user's home directory (or a specific project directory)
      - ${BIND_DIR:-./}:${MOUNT_POINT:-/home/workspace}:rw
      # Mount devices for hardware access
      - /dev:/dev
      - /run/udev:/run/udev
      # X11 forwarding for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      # Set the display for GUI apps
      - DISPLAY=${DISPLAY}
      # Standard terminal settings
      - TERM=xterm-256color
      # Custom environment variables from the script
      - VINE_CONTAINER=1
      - MOUNT_POINT=${MOUNT_POINT:-/home/workspace}

    working_dir: ${MOUNT_POINT:-/home/workspace}

    # Keep the container running
    stdin_open: true
    tty: true
